name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-simulator:
    name: Build (simulador, sin firma)
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Ruby y Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: |
          gem install fastlane

      - name: Comprobar versión de Xcode
        run: xcodebuild -version

      - name: Ejecutar lane de CI
        run: fastlane ios build_ci
