name: iOS Ship to TestFlight

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: "Notas de esta build"
        required: false
        default: "Build automática desde GitHub Actions"

jobs:
  ship:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Ruby y Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: |
          gem install fastlane

      - name: Mostrar versión de Xcode
        run: xcodebuild -version

      - name: Verificar proyecto Xcode
        id: checkproj
        run: |
          if ls *.xcodeproj 1> /dev/null 2>&1; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Salir si no hay .xcodeproj (placeholder)
        if: steps.checkproj.outputs.found == 'false'
        run: |
          echo "Aún no existe el proyecto Xcode. Nada que enviar."
          exit 0

      - name: Guardar .p8 de App Store Connect desde secret (base64)
        run: |
          mkdir -p fastlane
          echo "$APP_STORE_CONNECT_API_P8_BASE64" | base64 -d > fastlane/AuthKey_${APP_STORE_KEY_ID}.p8
        env:
          APP_STORE_CONNECT_API_P8_BASE64: ${{ secrets.APP_STORE_CONNECT_API_P8_BASE64 }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}

      - name: Ejecutar Fastlane (beta)
        env:
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          CHANGELOG: ${{ github.event.inputs.changelog }}
        run: |
          # Si tu Fastfile usa match, exporta también MATCH_PASSWORD aquí.
          fastlane ios beta
